// src/seed/week1Data.js
// Official Week 1 data (matches 1–15 only) taken from the JSON export.

export const week1Results = [
    {
      matchNo: 1,
      teamAId: "team-enoch",
      teamBId: "team-mdu",
      standbyId: "team-nk",
      goalsA: 1,
      goalsB: 0,
      winnerId: "team-enoch",
      isDraw: false,
    },
    {
      matchNo: 2,
      teamAId: "team-enoch",
      teamBId: "team-nk",
      standbyId: "team-mdu",
      goalsA: 1,
      goalsB: 1,
      winnerId: null,
      isDraw: true,
    },
    {
      matchNo: 3,
      teamAId: "team-nk",
      teamBId: "team-mdu",
      standbyId: "team-enoch",
      goalsA: 2,
      goalsB: 2,
      winnerId: null,
      isDraw: true,
    },
    {
      matchNo: 4,
      teamAId: "team-mdu",
      teamBId: "team-enoch",
      standbyId: "team-nk",
      goalsA: 0,
      goalsB: 3,
      winnerId: "team-enoch",
      isDraw: false,
    },
    {
      matchNo: 5,
      teamAId: "team-enoch",
      teamBId: "team-nk",
      standbyId: "team-mdu",
      goalsA: 0,
      goalsB: 0,
      winnerId: null,
      isDraw: true,
    },
    {
      matchNo: 6,
      teamAId: "team-nk",
      teamBId: "team-mdu",
      standbyId: "team-enoch",
      goalsA: 0,
      goalsB: 2,
      winnerId: "team-mdu",
      isDraw: false,
    },
    {
      matchNo: 7,
      teamAId: "team-mdu",
      teamBId: "team-enoch",
      standbyId: "team-nk",
      goalsA: 3,
      goalsB: 0,
      winnerId: "team-mdu",
      isDraw: false,
    },
    {
      matchNo: 8,
      teamAId: "team-mdu",
      teamBId: "team-nk",
      standbyId: "team-enoch",
      goalsA: 1,
      goalsB: 2,
      winnerId: "team-nk",
      isDraw: false,
    },
    {
      matchNo: 9,
      teamAId: "team-nk",
      teamBId: "team-enoch",
      standbyId: "team-mdu",
      goalsA: 1,
      goalsB: 2,
      winnerId: "team-enoch",
      isDraw: false,
    },
    {
      matchNo: 10,
      teamAId: "team-enoch",
      teamBId: "team-mdu",
      standbyId: "team-nk",
      goalsA: 1,
      goalsB: 1,
      winnerId: null,
      isDraw: true,
    },
    {
      matchNo: 11,
      teamAId: "team-enoch",
      teamBId: "team-nk",
      standbyId: "team-mdu",
      goalsA: 0,
      goalsB: 2,
      winnerId: "team-nk",
      isDraw: false,
    },
    {
      matchNo: 12,
      teamAId: "team-nk",
      teamBId: "team-mdu",
      standbyId: "team-enoch",
      goalsA: 0,
      goalsB: 1,
      winnerId: "team-mdu",
      isDraw: false,
    },
    {
      matchNo: 13,
      teamAId: "team-mdu",
      teamBId: "team-enoch",
      standbyId: "team-nk",
      goalsA: 1,
      goalsB: 0,
      winnerId: "team-mdu",
      isDraw: false,
    },
    {
      matchNo: 14,
      teamAId: "team-mdu",
      teamBId: "team-nk",
      standbyId: "team-enoch",
      goalsA: 2,
      goalsB: 0,
      winnerId: "team-mdu",
      isDraw: false,
    },
    {
      matchNo: 15,
      teamAId: "team-mdu",
      teamBId: "team-enoch",
      standbyId: "team-nk",
      goalsA: 0,
      goalsB: 0,
      winnerId: null,
      isDraw: true,
    },
  ];
  
  export const week1Events = [
    {
      id: "1762962442344",
      type: "goal",
      teamId: "team-enoch",
      scorer: "Enoch",
      assist: "Uhone",
      timeSeconds: 161,
      matchNo: 1,
    },
    {
      id: "1762962744436",
      type: "goal",
      teamId: "team-enoch",
      scorer: "Munya",
      assist: null,
      timeSeconds: 89,
      matchNo: 2,
    },
    {
      id: "1762962997420",
      type: "goal",
      teamId: "team-nk",
      scorer: "Dayaan",
      assist: null,
      timeSeconds: 300,
      matchNo: 2,
    },
    {
      id: "1762963088405",
      type: "goal",
      teamId: "team-nk",
      scorer: "Zizou",
      assist: "Kolobe",
      timeSeconds: 65,
      matchNo: 3,
    },
    {
      id: "1762963181489",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Chad",
      assist: "Josh",
      timeSeconds: 157,
      matchNo: 3,
    },
    {
      id: "1762963259163",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Scott",
      assist: "Josh",
      timeSeconds: 235,
      matchNo: 3,
    },
    {
      id: "1762963281145",
      type: "goal",
      teamId: "team-nk",
      scorer: "Dr Babs",
      assist: "Dayaan",
      timeSeconds: 257,
      matchNo: 3,
    },
    {
      id: "1762963492293",
      type: "goal",
      teamId: "team-enoch",
      scorer: "Barlo",
      assist: "Enoch",
      timeSeconds: 103,
      matchNo: 4,
    },
    {
      id: "1762963623483",
      type: "goal",
      teamId: "team-enoch",
      scorer: "Munya",
      assist: null,
      timeSeconds: 233,
      matchNo: 4,
    },
    {
      id: "1762963695269",
      type: "goal",
      teamId: "team-enoch",
      scorer: "Uhone",
      assist: null,
      timeSeconds: 300,
      matchNo: 4,
    },
    {
      id: "1762964219992",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Humbu",
      assist: null,
      timeSeconds: 121,
      matchNo: 6,
    },
    {
      id: "1762964306278",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Josh",
      assist: "Scott",
      timeSeconds: 207,
      matchNo: 6,
    },
    {
      id: "1762964602833",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Chad",
      assist: "Scott",
      timeSeconds: 138,
      matchNo: 7,
    },
    {
      id: "1762964658993",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Josh",
      assist: null,
      timeSeconds: 194,
      matchNo: 7,
    },
    {
      id: "1762964711494",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Scott",
      assist: "Josh",
      timeSeconds: 246,
      matchNo: 7,
    },
    {
      id: "1762964902302",
      type: "goal",
      teamId: "team-nk",
      scorer: "Anathi",
      assist: "Zizou",
      timeSeconds: 78,
      matchNo: 8,
    },
    {
      id: "1762964962360",
      type: "goal",
      teamId: "team-nk",
      scorer: "Kolobe",
      assist: "Zizou",
      timeSeconds: 138,
      matchNo: 8,
    },
    {
      id: "1762965037495",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Josh",
      assist: "Chad",
      timeSeconds: 213,
      matchNo: 8,
    },
    {
      id: "1762965391231",
      type: "goal",
      teamId: "team-nk",
      scorer: "Nkululeko",
      assist: "Kolobe",
      timeSeconds: 213,
      matchNo: 9,
    },
    {
      id: "1762965433907",
      type: "goal",
      teamId: "team-enoch",
      scorer: "Barlo",
      assist: "Munya",
      timeSeconds: 255,
      matchNo: 9,
    },
    {
      id: "1762965487564",
      type: "goal",
      teamId: "team-enoch",
      scorer: "Nkumbuzo",
      assist: "Mark",
      timeSeconds: 300,
      matchNo: 9,
    },
    {
      id: "1762965657568",
      type: "goal",
      teamId: "team-enoch",
      scorer: "Uhone",
      assist: "Enoch",
      timeSeconds: 25,
      matchNo: 10,
    },
    {
      id: "1762965802299",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Humbu",
      assist: null,
      timeSeconds: 169,
      matchNo: 10,
    },
    {
      id: "1762966230476",
      type: "goal",
      teamId: "team-nk",
      scorer: "Anathi",
      assist: null,
      timeSeconds: 240,
      matchNo: 11,
    },
    {
      id: "1762966246304",
      type: "goal",
      teamId: "team-nk",
      scorer: "Kolobe",
      assist: null,
      timeSeconds: 256,
      matchNo: 11,
    },
    {
      id: "1762966561613",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Chad",
      assist: "Humbu",
      timeSeconds: 218,
      matchNo: 12,
    },
    {
      id: "1762966798044",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Scott",
      assist: null,
      timeSeconds: 107,
      matchNo: 13,
    },
    {
      id: "1762979730026",
      type: "shibobo",
      teamId: "team-nk",
      scorer: "Dayaan",
      assist: null,
      timeSeconds: 95,
      matchNo: 14,
    },
    {
      id: "1762979738493",
      type: "shibobo",
      teamId: "team-mdu",
      scorer: "Josh",
      assist: null,
      timeSeconds: 103,
      matchNo: 14,
    },
    {
      id: "1762979747195",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Josh",
      assist: "Humbu",
      timeSeconds: 112,
      matchNo: 14,
    },
    {
      id: "1762979755521",
      type: "goal",
      teamId: "team-mdu",
      scorer: "Chad",
      assist: null,
      timeSeconds: 120,
      matchNo: 14,
    },
  ];
  